### ISSUE TITLE
the link about Autotiler 

### ISSUE THREAD

**Issue by LinRui9531** [pulp-platform/pulp-dronet#1]
Hi,
Thanks for your great work.
But i met some problems when running PULP-DroNet. In section 2.2, i may not find the correct Autotiler link.
I downloaded files from the [https://github.com/GreenWaves-Technologies/autotiler](url) and [https://greenwaves-technologies.com/get-auto-tiler/](url). But the hierarchies were both different from the one given in readme. 

Could you give me the correct Autotiler link? Thx.

**Comment by DP8** [comment]
Hi,
you should follow -- step by step -- the installation procedure described in Sec. 2.2, and 2.3 of the README. If you want to do something different is up to you. You can also see the link looking at the git files, because (as it is written in the README) the Autotiler it is a git-submodule.
