### ISSUE TITLE
Trained model of pulp-dronet V2

### ISSUE THREAD

**Issue by Ramseyous0109** [pulp-platform/pulp-dronet#11]
Hello, I'm recently studying on your work and I'm trying to flash this work on AI-deck. I'm wondering if you have a trained model available for pulp-dronet V2 on AI-deck. Thanks for your reply.

**Comment by LorenzoLamberti94** [comment]
Hi, 
you can find all the pretrained models in this folder

https://github.com/pulp-platform/pulp-dronet/tree/master/pulp-dronet-v2/model 
Best, Lorenzo
