### ISSUE TITLE
Lost part Himax dataset？

### ISSUE THREAD

**Issue by ChenMathilda** [pulp-platform/pulp-dronet#12]
Hi，
I try  to reshow the PULP_DronetV2 on crazyflie+aideck.

 **About Himax dataset test01-test24**
And I find that in the final dataset structure, you mentioned that Himax  dataset test01-test24:
https://github.com/pulp-platform/pulp-dronet/tree/master/pulp-dronet-v2#:~:text=HMB_1_3900/%20%23%20Udacity_Dataset%0A%E2%94%82%20%20%20%E2%94%9C%E2%94%80%E2%94%80%20...%0A%E2%94%82%20%20%20%E2%94%9C%E2%94%80%E2%94%80%20HMB_6/%0A%7C-,%E2%94%82%20%20%20%E2%94%9C%E2%94%80%E2%94%80%20test_01/%20%23%20Himax_Dataset%0A%E2%94%82%20%20%20%E2%94%9C%E2%94%80%E2%94%80%20...%0A%E2%94%82%20%20%20%E2%94%94%E2%94%80%E2%94%80%20test_24/,-%E2%94%9C%E2%94%80%E2%94%80%20himax/%0A%E2%94%82%20%20%20%E2%94%94%E2%94%80%E2%94%80%20jpg/%0A%E2%94%82%20%20%20%20%20%20%20%E2%94%94%E2%94%80%E2%94%80%20testing
but in the link you given,there doesn't exist those datasets, only has test dataset.
https://github.com/pulp-platform/Himax_Dataset
So, I want know if those losted-datasets are necessaried in this project?

Regards,
Mathilda.

**Comment by Hugh-Chang** [comment]
Hi @ChenMathilda @LorenzoLamberti94, 
I have the same questions as your Q1. I didn't find out the training and validation set of HiMax. 
Regards
Yingxiu Chang

**Comment by ChenMathilda** [comment]
> Hi @ChenMathilda @LorenzoLamberti94, I have the same questions as your Q1. I didn't find out the training and validation set of HiMax. Regards Yingxiu Chang
Hi，
I still didn't find this Dataset.
But this dataset does not affect our understanding of the network, it just affects the accuracy of the network. So I am not looking for this dataset later.
