### ISSUE TITLE
The drone doesnt fly

### ISSUE THREAD

**Issue by SitSaw17** [pulp-platform/pulp-dronet#18]
hi
I have been trying to replicate this project with Crazyflies 2.0 and ai-deck. I have followed the instruction and managed to deploy the code into the drone but when I restart the drone nothing happens, any idea why?

![Screenshot_from_2022-03-22_20-33-40](https://user-images.githubusercontent.com/98044468/159562112-09a82747-3d40-4328-ab0d-a95f98dff23a.png)

**Comment by ChenMathilda** [comment]
> I have been trying to replicate this project with Crazyflies 2.0 and ai-deck. I have followed the instruction and managed to deploy the code into the drone but when I restart the drone nothing happens, any idea why?

Hi，
Did you modified the code on Crazyflie side？
According to my understanding, there is no Crazyflie-side control code in this repository, so we need to look for it, or write the Crazyflie-side control code ourselves.

**Comment by sithichot** [comment]
Hi
i found an old cf control for pulp-shield https://github.com/DP8/crazyflie-firmware/blob/master/src/deck/drivers/src/pulp_shield.c.
I couldn't complie it since i am using a newer version of gap_sdk. I am trying to modify ai_deck.c now instead

**Comment by ChenMathilda** [comment]
> Hi i found an old cf control for pulp-shield https://github.com/DP8/crazyflie-firmware/blob/master/src/deck/drivers/src/pulp_shield.c. I couldn't complie it since i am using a newer version of gap_sdk. I am trying to modify ai_deck.c now instead

Hi,
Looking forward to hearing from you.
By the way, did you achieved the communication between AI-deck and CF throught uart ? 
According to my understanding, CF need to fly autonomously based on network predictions. The network prediction results should be transmitted to Crazyflie via uart.
Regard，
Mathilda

**Comment by sithichot** [comment]
i manage to flash pulp-shield firmware but still nothing, so it might be as you said with the cf uart. I haven't manage to get the test_uart examples to work either.

**Comment by sithichot** [comment]
![Screenshot from 2022-04-13 13-21-50](https://user-images.githubusercontent.com/39099468/163169693-f449b66e-8273-43b4-b823-4eaf47809868.png)
This is from the cfclient console at start up

**Comment by ChenMathilda** [comment]
> i manage to flash pulp-shield firmware but still nothing, so it might be as you said with the cf uart. I haven't manage to get the test_uart examples to work either.

Hi, is there any progress recently? About the transfer between AI-deck and CF, here is an example：
https://github.com/bitcraze/aideck-gap8-examples/blob/master/examples/other/test_functionalities/uart_send_char/test.c
and in this page,you can find Bitcraze & Greenwave's workshop( with video), uart is in Session3: https://github.com/pulp-platform/AI-deck-workshop.
What‘s more, do you have any progress on the deployment of DroNet?
Best wishes!
