### ISSUE TITLE
make clean all Error under /pulp-dronet/pulp-dronet-v2/gapflow

### ISSUE THREAD

**Issue by ChenMathilda** [pulp-platform/pulp-dronet#21]
Hi，
I try `make clean all ` under `/pulp-dronet/pulp-dronet-v2/gapflow `. But met the following errors: https://pastebin.pl/view/9e1a8baf.
```
# part of Error log
Error: Graph stacked tensor S16_Output, input tensor Output_1 is also defined as a graph local or graph argument
Execution aborted
```
I don't konw how to solve it.
Hoping I can get solutions here.

My code environment:
`gap_sdk = 3.8, python =3.7, ubuntu18.04.`
Using the onnx export by` /pulp-dronet/pulp-dronet-v2/model/dronet_v2_gapflow_original_himax.pth` and `/pulp-dronet/pulp-dronet-v2/model/dronet_v2_gapflow_original.pth`
I tried `gap_sdk = 3.9` but got more Errors: https://pastebin.pl/view/8518979a

Regards,
Mathilda

**Comment by knmcguire** [comment]
Just for reference, the SDK version needs to be 3.9.1. See this discussion: https://github.com/orgs/bitcraze/discussions/59

Probably the readme should be updated then. https://github.com/pulp-platform/pulp-dronet/blob/master/pulp-dronet-v2/README.md
