### ISSUE TITLE
I encountered the following problem when trying to Build and run on GVSoC after Use DORY to generate the C code.

### ISSUE THREAD

**Issue by zyxzxy** [pulp-platform/pulp-dronet#27]
Hi，
I encountered the following problem when trying to Build and run on GVSoC after Use DORY to generate the C code.

DORY_network/src/main.c:42:10: fatal error: tools/frame_streamer.h: No such file or directory
 #include "tools/frame_streamer.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/home/zyx/gap_gnu_toolchain/gap_gnu_toolchain/gap_gnu_toolchain/gap8_openocd/gap_sdk/tools/rules/pulp_rules.mk:205: /home/zyx/下载/pulp-dronet-master/tiny-pulp-dronet-v3/drone-applications/gap8-dronet-app/pulp-dronet-v3/BUILD/GAP8_V2/GCC_RISCV/DORY_network/src/main.o] Error 1

My gap sdk version is GAP SDK 3.9.1.After I found the frame_streamer.h file and imported it, I encountered a new problem.

/usr/lib/gap_riscv_toolchain/bin/../lib/gcc/riscv32-unknown-elf/7.1.1/../../../../riscv32-unknown-elf/bin/ld: cannot find -lgaptools
collect2: error: ld returned 1 exit status
make: *** [/home/zyx/gap_gnu_toolchain/gap_gnu_toolchain/gap_gnu_toolchain/gap8_openocd/gap_sdk/tools/rules/pulp_rules.mk:212: /home/zyx/下载/pulp-dronet-master/tiny-pulp-dronet-v3/drone-applications/gap8-dronet-app/pulp-dronet-v3/BUILD/GAP8_V2/GCC_RISCV/main] Error 1
How can I solve these problems?
Best wishes！
ZHANG

**Comment by LorenzoLamberti94** [comment]
it's a problem of the gap_sdk, you can check their issues
https://github.com/GreenWaves-Technologies/gap_sdk/issues

**Comment by zyxzxy** [comment]
Thanks for your reply, I saw the same question you asked. Do you still remember how to solve the problem at that time? I have successfully generated the pulp-dronet-v3 code, but it still cannot run on gap8. How should I adjust my gap_sdk? Looking forward to your reply. Thank you very much.

**Comment by r-bt** [comment]
@zyxzxy Did you ever solve this issue? I am experiencing it now
