### ISSUE TITLE
About the rotational velocity

### ISSUE THREAD

**Issue by SUJUSTDO** [pulp-platform/pulp-dronet#28]
Hi, in the description of the dataset, The yaw rate label, representing the rotational velocity. values are in the [-1, +1] range. But why are the actual values in **labels_partitioned.csv** not in the [-1, +1] range? For example -20, etc.

**Comment by LorenzoLamberti94** [comment]
hi, labels_partitioned.csv has actual yaw rates, e.g., 120 deg/s, while the final label has been normalized in the [-1,1] range
