### ISSUE TITLE
Hello,How can I buy a pulp-shield board?

### ISSUE THREAD

**Issue by Jinghao-coding** [pulp-platform/pulp-dronet#3]

**Comment by wei-1006** [comment]
Same question.
Can I buy the PULP-Shield and PULP JTAG converter board from you?
Since I have no background of PCB, I have no idea about the technology(like material) you used to product the board.
I'm really interested in this project, so I really want to try it.
Thanks.

**Comment by FrancescoConti** [comment]
Hi, as far as we know Bitcraze should release  an AI-Deck in the near future that will be in part based on the open source PULP Shield design (see https://www.bitcraze.io/2019/10/sneak-peak-of-the-ai-deck/).

I don’t understand the second question tbh. If you mean whether we’ll release  “DroNet without shield”, that is not planned at the moment as the microcontroller used by the CF2/2.1 does not have enough compute performance to run an AI model like DroNet with sufficient speed for real time operation.

**Comment by wei-1006** [comment]
Hi, for the second question, I mean that will the last section of README(6.Run PULP-DroNet on the Crazyflie 2.0/2.1) release recently?

**Comment by DP8** [comment]
Yes, it will be included in the near future. Stay tuned ;-)
