### ISSUE TITLE
Not able to flash pulp-dronet for the ai-deck

### ISSUE THREAD

**Issue by danieldennett** [pulp-platform/pulp-dronet#4]
Dear @DP8 and @FrancescoConti ,

At the moment I am working with the ai-deck from BitCraze and I am trying to flash the pulp-dronet on it. For this I also started working from the gap_sdk which incorporates the necesarry pulp-sdk elements. There I encountered a bug with bridge and runtime #MNIST example error: Protocol version mismatch between bridge and runtime https://github.com/GreenWaves-Technologies/gap_sdk/issues/101. I was wondering if this is also the case for the pulp-dronet as I got stuck at `starting execution`.

This error in part can also be caused by not having the correct configuration settings for the ai-deckv1 and ai-deckv2 as I got the same error message when working with the gap_sdk and the ai-deck with gap8_v1, when I found the correct settings. I managed to run the helloworld example on both ai-decks. So if this is the case, than could you point me in the right directions where to find the possible settings? I have looked and till now I was not able to combine the information from the platform and gap settings to make an ai-deck_v1 or ai-deck_v2 compatible setting. Thanks in advance. 

```
user@bitcrazeDemo:~/pulp-dronet/weights$ plpbridge --cable=ftdi --chip=gap flash_erase_chip flash_write --addr=0 --file=./WeightsPULPDroNet.raw
Notifying to boot code that we are doing a JTAG boot
Found ftdi device i:0x15BA:0x2A:0
Connecting to ftdi device i:0x15BA:0x2A:0
Loading binary through jtag
Notifying to boot code that we are doing a JTAG boot
Loading binaries
Loading /home/user/pulp-sdk/pkg/sdk/dev/install/bin/flasher-gap
Loading section (base: 0x1b000004, size: 0x3ec)
Loading section (base: 0x1b0003f0, size: 0x840)
Loading section (base: 0x1c000000, size: 0x62dc)
Init section to 0 (base: 0x1c0062dc, size: 0x1b0)
Loading section (base: 0x1c00648c, size: 0x10)
Starting execution
^CTerminated

```

**Comment by DP8** [comment]
Hi,
did you try also with the pulp-sdk?
https://github.com/pulp-platform/pulp-dronet#sdk
