### ISSUE TITLE
Do you use any deck from Bitcraze in this project?

### ISSUE THREAD

**Issue by wei-1006** [pulp-platform/pulp-dronet#5]
Hi,
I'm curious that do you setup any deck like flow deck on the crazyflie to make it fly steadily at certain height?
If not,  what's your method to control it ?

Thanks!
Yang

**Comment by wei-1006** [comment]
Hi,
I also want to ask that do you use Bitcraze Crazyradio PA to send any command, or you just use PULP Shield to tell the drone to take off?

Thanks!
Yang

**Comment by DP8** [comment]
Hi,
we use our PULP-Shield in combination with the BC flow-deck. 
The entire project is about autonomous navigation, therefore, no commands from any external device, everything is running onboard. The take-off it is done with a timer in the CF's firmware, you load the binary (i.e., pulp-dronet running on PULP) then the timer starts, after a few seconds it takes off and then it flies autonomously on the basis of what the onboard CNN is deciding.
