### ISSUE TITLE
In the future, Can I run DroNet on AI-Deck?

### ISSUE THREAD

**Issue by apple1987** [pulp-platform/pulp-dronet#6]
As far as I know, the AI-Deck chip is about to be released, so can we integrate the AI-Deck on the drone Crazyflie2.1 and run our DroNet?

**Comment by tobbeanton** [comment]
This is the plan but since some things has changed the code needs to be adapted for this. E.g. the communication is now UART instead of SPI and there is now a possibility to stream the video over wifi. Also the SDK has diverged a bit between PULP and GAP8 and needs work.
